#+TITLE: Patchwork, the RPG
#+AUTHOR: Olivier Rey
#+DATE: 2021-09-26
#+STARTUP: overview

This is a very basic RPG which objective is to be implemented in JS by an AI. It copies a lot of other games.

* 1. Creating a PC

** 1.1. Features

Several possibilities:
- The character starts at 6 on each 4 features and has 14 points to assign;
- The player launches 1D6+6 4 times and assign the results to the features;
- The player launches 1D6+6 5 times, keep the 4 best scrores and assign the results to the features.

#+ATTR_HTML: :border 2 :rules all :frame border
| Feature    | Creation | Comments                                         | Code |
|------------+----------+--------------------------------------------------+------|
| PHYSICAL   |     6-12 | Anything physical skill including combat         | PHY  |
| MENTAL     |     6-12 | Any intelligence skill including mental health   | MEN  |
| CHANCE     |     6-12 | Better get lucky sometimes                       | CHA  |
| MAGICAL    |     6-12 | Magic, faith, the Force, etc., to act and resist | MAG  |
| HIT POINTS |   PHY+12 | At 0, le PC is dead                              | HP   |

Those scores will evolve during the session. The scores determined at PC creation are the maximum the PC can be when fully rested.

The scores can also evolve during the life of the PC.

*** Examples

Jenny plays a female well known archeologist, Professor Claudia Heichmuller in a modern setting. She chooses to assign the 14 points by herself.

*Claudia Heichmuller*
#+ATTR_HTML: :border 2 :rules all :frame border
| PHY | 9 (6+3)   |
| MEN | 12 (6+6)  |
| CHA | 11 (6+5)  |
| MAG | 6 (6+0)   |
| HP  | 21 (9+12) |

Tom plays a male detective, John Tracker, that senses magic in a modern setting. He decides to roll 4 times and gets 4, 6, 5 and 3.

*John Tracker*
#+ATTR_HTML: :border 2 :rules all :frame border
| PHY | 12 (6+6)   |
| MEN | 11 (6+5)   |
| CHA | 10 (6+4)   |
| MAG | 9 (6+3)    |
| HP  | 24 (12+12) |

** 1.2. Equipment

To be seen with the GM and the story.

* 2. Game mechanics

** Testing competences PHY and MEN

All testing is done *strictly under* the score. Roll 2D6 strictly under the feature to succeed. *Double 6 always fails*.

For PHY and MEN, the GM can had:
- A *penalty*: For instance, shooting in the dark, penalty = +4 to the player's PHY dice roll.
- A *bonus*: For instance, finding an information everywhere on the news, bonus = -4 to the player's MEN dice roll.

** Testing chance

The CHA feature is working like a pool. Your CHA score represents the number of D6 you will be able to spend during the adventure to alter the results of failed tests.

The cool thing is that, provided you succed in a test of CHA pool, you can alter any roll after the feature test is failed. But, for sure, you progressively loose points in your CHA pool when you consume them.

To test your luck, roll 2D6 under your CHA pool value. If the score is *inferior or equal to the CHA pool, that's a success*.

If the test does not work, you loose the points anyway. The GM can decide if something badder happens (it is generally bad enough to have tried a luck test...).

Note: CHA cannot have penalties on tests.

*** Sample

Claudia is hanging on a suspension bridge. She missed her PHY test by rolling 8 on 2D6, test under 9 with a penalty of 3 because she is carring a heavy gold artifact. 8+3=11 which is bigger than 9.

She decides to take 2 points of CHA from her pool of 11. She rolls 2D6: 3 and 1. That makes 4 to substract from the 12 missed roll which gives 11-4=7. She succeeds in getting out of the bridge with the gold artifact.

Claudia has now 9 points in her CHA pool for the rest of the adventure.

** Testing magic

Testing magic can be done in 3 situations:
1. Sensing magic,
2. Resisting magic,
3. Casting spells.




