#+TITLE: La grande liste des intrigues des JDR
#+AUTHOR: Olivier Rey
#+DATE: 2021-04-25
#+STARTUP: overview

#+ATTR_HTML: :border 2 :rules all :frame border
| Concepteur               | John Ross                                          |
| Version traduite         | Version originale 2002                             |
| PDF original             | [[file:The_Big_List_of_RPG_Plots_by_S._John_Ross.pdf]] |
| Traduction et adaptation | O. Rey Avril 2021                                  |


* Une aide aux MJ, par John Ross, Version 2

Ce qui suit est un ensemble de sujets divers... ma collection d'intrigues de JDR, dans une forme abstraite. J'ai construit cela en examinant les démarrages de centaines d'aventures publiées pour toues les systèmes de jeu (en incluant les systèmes chers à mon coeur n'étant plus imprimés), en tentant de les réduire à des dénominateurs communs. Les résultats sont publiés ici : arbitraires et parfois redondants. Néanmoins, je me retourne vers cette liste quand je sèche sur un nouveau démarrage pour la prochaine session hebdomadaire de ma campagne, quelque soit la campagne. Cela m'aide à ne pas tomber dans les ornières thématiques (ce que je préfère le moins). Avec un peu de chance, cela remplira la même fonction pour vous.

/Note/ : Les intrigues sont arrangées par titre et par ordre alphabétique. Comme les titres sont arbitraires, l'ordre n'a pas d'importance particulière. Et si vous voulez du blabla shakespearien en cinq actes, des intrigues complexes, l'Homme contre Lui-Même ou d'autres stupidités littéraires, essayez le [[https://www.writersdigest.com/][Writer's Digest]]. On n'est pas à Oxford, mec.

* Tout vieux port dans une tempête

Les PJ cherchent un abri contre les éléments ou contre une autre menace, et trouvent un endroit pour se terrer. Ils s'aperçoivent qu'ils sont tombés sur quelque chose de dangereux, de secret, ou de surnaturel, et donc doivent y faire face afin de trouver un peu de repos.

/Thèmes et rebondissements courants/ :
- L'abri contient la cause de la menace que les PJ tentaient d'éviter.
- L'abri cache une base cachée.
- Les PJ ne doivent pas seulement se battre pour un abri, mais ils doivent se battre pour survivre.
- L'endroit est un véritable abri d'un certain genre, mais les PJ ne sont pas les bienvenus et ils doivent gagner les coeurs ou les intellects pour gagner leur lit pour la nuit.

* Mieux vaut tard que jamais

Des méchants sont arrivés et ils ont fait des trucs de méchants. Les PJ n'ont rien compris au film. Les méchants ont décidé de se faire la malle, et les PJ en ont entendu parler à temps pour se lancer à leur poursuite avant qu'ils ne rejoignent leur repaire, leur pays, leurs lignes ennemies, etc.

/Thèmes et rebondissements courants/ :
- Les méchants se sont enfuis en volant un moyen de transport que les PJ maîtrisent mieux qu'eux.
- Les méchants empruntent une voie détournée (métaphoriquement ou réellement), tentant de se cacher ou de se fondre dans l'environnement (souvent hostile aux PJ).
- Si les méchants passent la "ligne d'arrivée" de l'aventure (passer la frontière, passer en vitesse lumière, etc.), il n'est plus possible de les poursuivre au delà.

* Chantage

Habituellement, en usant de tricherie (et parfois en fouillant dans le passé des PJ), un adversaire possède quelque chose qui est susceptible de faire obéir les PJ. La menace peut être de n'importe quel type depuis une menace physique jusqu'à une menace sociale, mais l'intrigue dépend du fait que le méchant possède quelque chose - même si ce n'est une information - que ne possède pas les autres. Avec cela, il contrôle les PJ en leur disant de faire des choses qu'ils ne veulent pas faire. Les PJ doivent briser le cercle du chantage, priver le méchant de son avantage et le rendre temporairement satisfait tandis qu'ils le font.

/Thèmes et rebondissements courants/ :
- L'accroche de l'aventure implique que les personnages doivent d'abord aider le méchant, ce qui permet à ce dernier de les faire chanter (situation cynique).
- Pour réussir à se sortir du chantage, les PJ doivent contacter d'autres victimes.
- Les PJ ne sont pas les victimes mais la victime est quelqu'un qu'ils apprécient ou qu'ils sont chargés de protéger.

* Cambriolage

Objectif de la mission : pénétrer dans un endroit dangereux, et rapporter quelque chose  vital ou ramener une personne. Surmonter toutes les difficultés de l'endroit pour y parvenir.

/Thèmes et rebondissements courants/ :
- L'objectif n'est pas de rapporter quelque chose, mais de détruire quelque chose, ou d'interférer dans un processus en cours :
  + Détruire le générateur de champ de force,
  + Tuer le méchant roi,
  + Interrompre le sort avant qu'il ne soit lancé,
  + Ruiner les plans d'invasion,
  + Fermer un portail,
  + Etc.
- L'objectif a changé de place.
- L'objectif est une information qui doit être diffusée ou publiée dans le secteur dès qu'elle a été trouvée.
- Le travail doit être fait dans la plus grande discrétion.
- Les PJ ne savent pas que l'endroit est dangereux.
- Les PJ doivent remplacer une chose par une autre chose.




