#+TITLE: La grande liste des intrigues de JDR
#+AUTHOR: Olivier Rey
#+DATE: 2021-04-25
#+STARTUP: overview

#+ATTR_HTML: :border 2 :rules all :frame border
| Concepteur               | John Ross                                          |
| Version traduite         | Version originale 2002                             |
| PDF original             | [[file:The_Big_List_of_RPG_Plots_by_S._John_Ross.pdf]] |
| Traduction et adaptation | O. Rey Avril 2021                                  |


* Une aide aux MJ, par John Ross, Version 2

Ce qui suit est un ensemble de sujets divers... ma collection d'intrigues de JDR, dans une forme abstraite. J'ai construit cela en examinant les démarrages de centaines d'aventures publiées pour toues les systèmes de jeu (en incluant les systèmes chers à mon coeur n'étant plus imprimés), en tentant de les réduire à des dénominateurs communs. Les résultats sont publiés ici : arbitraires et parfois redondants. Néanmoins, je me retourne vers cette liste quand je sèche sur un nouveau démarrage pour la prochaine session hebdomadaire de ma campagne, quelque soit la campagne. Cela m'aide à ne pas tomber dans les ornières thématiques (ce que je préfère le moins). Avec un peu de chance, cela remplira la même fonction pour vous.

/Note/ : Les intrigues sont arrangées par titre et par ordre alphabétique. Comme les titres sont arbitraires, l'ordre n'a pas d'importance particulière. Et si vous voulez du blabla shakespearien en cinq actes, des intrigues complexes, l'Homme contre Lui-Même ou d'autres stupidités littéraires, essayez le [[https://www.writersdigest.com/][Writer's Digest]]. On n'est pas à Oxford, mec.

* 1. Tout vieux port dans une tempête

Les PJ cherchent un abri contre les éléments ou contre une autre menace, et trouvent un endroit pour se terrer. Ils s'aperçoivent qu'ils sont tombés sur quelque chose de dangereux, de secret, ou de surnaturel, et donc doivent y faire face afin de trouver un peu de repos.

/Thèmes et rebondissements courants/ :
- L'abri contient la cause de la menace que les PJ tentaient d'éviter.
- L'abri cache une base cachée.
- Les PJ ne doivent pas seulement se battre pour un abri, mais ils doivent se battre pour survivre.
- L'endroit est un véritable abri d'un certain genre, mais les PJ ne sont pas les bienvenus et ils doivent gagner les coeurs ou les intellects pour gagner leur lit pour la nuit.

* 2. Mieux vaut tard que jamais

Des méchants sont arrivés et ils ont fait des trucs de méchants. Les PJ n'ont rien compris au film. Les méchants ont décidé de se faire la malle, et les PJ en ont entendu parler à temps pour se lancer à leur poursuite avant qu'ils ne rejoignent leur repaire, leur pays, leurs lignes ennemies, etc.

/Thèmes et rebondissements courants/ :
- Les méchants se sont enfuis en volant un moyen de transport que les PJ maîtrisent mieux qu'eux.
- Les méchants empruntent une voie détournée (métaphoriquement ou réellement), tentant de se cacher ou de se fondre dans l'environnement (souvent hostile aux PJ).
- Si les méchants passent la "ligne d'arrivée" de l'aventure (passer la frontière, passer en vitesse lumière, etc.), il n'est plus possible de les poursuivre au delà.

* 3. Chantage

Habituellement, en usant de tricherie (et parfois en fouillant dans le passé des PJ), un adversaire possède quelque chose qui est susceptible de faire obéir les PJ. La menace peut être de n'importe quel type depuis une menace physique jusqu'à une menace sociale, mais l'intrigue dépend du fait que le méchant possède quelque chose - même si ce n'est une information - que ne possède pas les autres. Avec cela, il contrôle les PJ en leur disant de faire des choses qu'ils ne veulent pas faire. Les PJ doivent briser le cercle du chantage, priver le méchant de son avantage et le rendre temporairement satisfait tandis qu'ils le font.

/Thèmes et rebondissements courants/ :
- L'accroche de l'aventure implique que les personnages doivent d'abord aider le méchant, ce qui permet à ce dernier de les faire chanter (situation cynique).
- Pour réussir à se sortir du chantage, les PJ doivent contacter d'autres victimes.
- Les PJ ne sont pas les victimes mais la victime est quelqu'un qu'ils apprécient ou qu'ils sont chargés de protéger.

* 4. Cambriolage

Objectif de la mission : pénétrer dans un endroit dangereux, et rapporter quelque chose  vital ou ramener une personne. Surmonter toutes les difficultés de l'endroit pour y parvenir.

/Thèmes et rebondissements courants/ :
- L'objectif n'est pas de rapporter quelque chose, mais de détruire quelque chose, ou d'interférer dans un processus en cours :
  + Détruire le générateur de champ de force,
  + Tuer le méchant roi,
  + Interrompre le sort avant qu'il ne soit lancé,
  + Ruiner les plans d'invasion,
  + Fermer un portail,
  + Etc.
- L'objectif a changé de place.
- L'objectif est une information qui doit être diffusée ou publiée dans le secteur dès qu'elle a été trouvée.
- Le travail doit être fait dans la plus grande discrétion.
- Les PJ ne savent pas que l'endroit est dangereux.
- Les PJ doivent remplacer une chose par une autre chose.

* 5. Conquérir le drapeau

Les PJ doivent sécuriser une cible militaire pour le compte des gentils. Des méchants sont là qui préfèrent ne pas être sécurisés. C'est le scénario tactique par excellence.

/Thèmes et rebondissements courants/ :
- Les PJ doivent former et/ou entraîner un groupe pour faire le travail à leurs côtés.
- Les PJ travaillent avec de fausses informations et la zone visée n'est pas telle que décrite dans ces informations.
- Les PJ doivent se coordonner avec un groupe allié (en mettant possiblement leurs rivalités de côté pour y parvenir).
- La zone visée contient :
  + Une population de gens fragiles ne devant pas être blessés dans la bataille ;
  + Des biens fragiles ou d'autres choses précieuses qui ne doivent pas être endommagés dans les tirs croisés.

* 6. Nettoyer la malédiction

Il existe un endroit où des choses mauvaises vivent. Les PJ doivent sécuriser la zone pour le compte de personnes gentilles, et éradiquer systématiquement tout danger.

/Thèmes et rebondissements courants/ :
- Les mauvaises choses ne peuvent pas être battues au travers d'un combat direct.
- Les PJ doivent apprendre des choses sur ces mauvaises choses pour pouvoir résoudre le problème.
- La maison hantée.
- La zone est infestée d'extraterrestres.
- La forêt sauvage.

* 7. Le régal du chercheur de trésors

Les PJ sont des chasseurs de trésors qui ont eu vent de l'existence d'une ruine chargée de trésors. Ils vont l'explorer, et ils doivent faire face à ses habitants surnaturels pour gagner leurs trésors et en sortir vivants.

/Thèmes et rebondissements courants/ :
- Le trésor lui-même est dangereux.
- Le trésor n'est pas dans une ruine, mais dans une région sauvage ou même caché dans un endroit "civilisé".
- Le trésor est la propriété légitime de quelqu'un d'autre.
- Le trésor a une volonté propre.

* 8. Ne mangez pas les violets (survie)

Les PJ échouent dans un endroit étrange, et doivent survivre en trouvant de la nourriture et un abri. Ils doivent ensuite s'inquiéter de comment rentrer chez eux.

/Thèmes et rebondissements courants/ :
- Les PJ ne doivent survivre que pour une courte période de temps en attendant que :
  + L'aide arrive,
  + Le navire et/ou la radio ou autre chose soi(en)t réparé(s). Dans les scénarios de "réparation", les PJ doivent parfois découvrir certains faits relatifs à l'environnement qui vont leur permettre de faire les réparations nécessaires.

* 9. Élémentaire, mon cher Watson

Un crime ou une atrocité a été commis(e) ; les PJ doivent le résoudre. Ils doivent interroger les témoins (et s'assurer qu'ils ne font pas tuer), rassembler des indices (et s'assurer qu'elles ne seront pas volées ou détruites). Ils doivent alors assembler des preuves à livrer aux autorités, ou faire la justice eux-mêmes.

/Thèmes et rebondissements courants/ :
- Les PJ travaillent à innocenter quelqu'un qui a été accusé (possiblement eux-mêmes).
- Les PJ doivent travailler aux côtés d'un enquêteur spécial, ou ils sont obligés de travailler avec un allié dont ils ne voulaient pas.
- Au milieu de l'aventure, les PJ sont retirés de l'affaire. La demande ou l'autorité pour enquêter est retirée (souvent du fait des manoeuvres politiques d'un adversaire).
- Le point culminant de l'histoire se passe dans un tribunal ou dans un autre endroit où l'on rend les jugements.
- L'échelle de ce genre d'aventures est variable, depuis un meurtre dans une petite ville jusqu'au scandale d'une pollution planétaire.

* 10. Service d'escorte

Les PJ disposent d'un objet de valeur ou sont en charge d'une personne importante. Ils doivent rapporter cet objet à son propriétaire légitime, ramener la personne dans un lieu protégé, etc. Ils doivent entreprendre un voyage dangereux dans lequel une ou plusieurs factions (et la chance et la malchance) vont tenter de leur soustraire la personne sous leur protection ou la chose en leur possession.

/Thèmes et rebondissements courants/ :
- La chose ou la personne est génératrice de problèmes, elle tente de s'évader ou de se détourner des PJ.
- La destination a été détruite ou s'est rendue au camp ennemi, et les PJ doivent prendre sur eux de résoudre le problème de la destination ou le problème de la chose ou de la personne elle-même.
- La personne protégée est un dissident politique.
- L'arrivée à la destination n'arrête pas l'histoire ; les PJ doivent alors négocier la personne ou la chose comme une marchandise (échange d'argent contre un otage par exemple).
- Les PJ doivent protéger leur cible sans que le cible ne soit au courant.

* 11. Une maison en ordre

Les PJ sont placés à la tête d'une grande opération (une compagnie commerciale, une baronnie féodale, la CIA, etc.) et doivent, malgré leur manque d'expérience dans ce domaine, la faire fonctionner et prospérer.

/Thèmes et rebondissements courants/ :
- Les PJ sont embarqués dans cette histoire parce que quelque chose d'important se prépare et l'ancienne garde se ménage une change de d'enfuir.
- Les paysans, voisins, employés, etc., en veulent aux PJ parce qu'ils n'apprécient pas leurs méthodes et que tout le monde aimait l'ancien patron.

* 12. La cavalerie arrive

Une personne, ou un groupe religieux, une nation, une galaxie, etc., est dans une situation périlleuse, si bien qu'ils ne peuvent survivre sans secours. C'est le boulot des PJ de les secourir. Dans certains scénarios, l'hameçon est aussi simple qu'un cri lointain ou un signal de détresse grésillant.

/Thèmes et rebondissements courants/ :
- La ou les victime(s) est/sont otage(s) ou soumises à un siège des forces ennemies et les PJ doivent faire face aux ravisseurs ou interrompre le siège.
- Il y a un risque que toute tentative de secours mettent la cavalerie dans le même bain que ceux doivent être secourus aggravant le problème.
- Les victimes à secourir ne sont pas des humains mais des animaux, des robots ou d'autres choses.
- La "victime" ne réalise pas qu'elle a besoin d'être secourue ; elle pense qu'elle fait quelque chose de raisonnable ou de sûr.
- La menace n'est pas le fait d'un méchant ; c'est un désastre naturel, un accident nucléaire, ou une épidémie.
- Les victimes ne peuvent pas partir ; quelque chose d'immobile et de vital doit être pris en charge sur le lieu de l'aventure.
- Les PJ démarrent comme faisant partie des victimes, doivent s'échapper, rassembler des forces ou des ressources afin de procéder comme indiqué ci-dessus.

* 13. La base cachée

Les PJ, durant leur voyage ou leur exploration, tombent sur un nid de méchants préparant la Grande Méchanceté. Ils doivent trouver le moyen d'avertir les gentils, ou entrer discrètement et neutraliser l'endroit, ou une combinaison des deux.

/Thèmes et rebondissements courants/ :
- Les PJ doivent comprendre comment utiliser les ressources locales pour se défendre ou avoir une chance contre les habitants.

* 14. Combien pour juste le bidule ?

Dans un endroit déterminé, quelque chose d'important et de valeur existe. Les PJ (ou leurs employeurs) le veulent, mais un ou plusieurs autres groupes aussi. Ceux qui vont l'obtenir pourront distancer les autres, mieux négocier avec les autochtones et apprendre le plus de choses sur la chose visée. Tous les group en compétition ont leur propre agenda et leurs propres ressources.

/Thèmes et rebondissements courants/ :
- Les autochtones demandent aux factions en compétition de se rassembler devant eux sans se combattre pour défendre leur cas.
- La chose de valeur était en route pour quelque part quand ce qui la transportait a été détruit ou a disparu.

* 15. Je vous demande pardon ?

Les PJ s'occupent de leurs affaires quand ils sont attaqués ou menacés. Ils ne savent pas pourquoi. Ils doivent résoudre le mystère des motivations de leurs attaquants, tout en continuant de repousser de nouvelles attaques. Ils doivent comprendre pour régler le problème.

/Thèmes et rebondissements courants/ :
- Les PJ ont quelque chose que les méchants veulent, mais ils ne le réalisent pas forcément.
- Les méchants veulent se venger de la mort d'un compatriote survenue dans une aventure précédente.
- Les méchants ont confondu les PJ avec d'autres personnes.

* 16. Une fourchette longue ou courte pour dîner avec un elfe ?

Les PJ sont une avant-garde diplomatique tendant de commencer (ou de consolider) des relations politiques ou commerciales avec une culture étrange. Tout ce qu'ils doivent faire est de passer une ou plusieurs journées dans des coutumes étrangères sans offenser personne... et les informations dont ils disposent sont à la fois incomplètes et dangereusement trompeuses.

/Thèmes et rebondissements courants/ :
- Les PJ ont été choisis par quelqu'un qui sait qu'ils n'étaient pas préparés pour cette expérience, un PNJ tentant de saboter leurs travaux (repérer ce méchant serait nécessaire pour éviter le désastre).

* 17. Regardez sans toucher

Les PJ sont dans la surveillance : espionnage d'une personne, recueil d'informations sur une bête dans la nature, exploration d'un nouveau secteur. Quelque soit l'échelle, le premier conflit (au moins au débat) est qu'ils ne doivent /que/ regarder, écouter et apprendre. Ils ne doivent pas établir de contact ou se faire connaître.

/Thèmes et rebondissements courants/ :
- La cible fait face à des problèmes, et les PJ doivent décider s'ils enfreignent la règle d'absence de contact pour organiser un sauvetage.

* 18. Chasse à l'homme

Une ou plusieurs personnes ont disparu: ils se sont enfuis, se sont perdus ou n'ont simplement pas donné de nouvelles depuis un certain temps. Ils manquent à quelqu'un qui souhaite leur retour. Les PJ sont appelés pour les retrouver et les ramener.

/Thèmes et rebondissements courants/ :
- La cible a été kidnappée, possiblement pour appâter les PJ.
- La cible est dangereuse et elle s'est échappée d'un établissement destiné à protéger le public de personnes de ce genre.
- La cible est quelqu'un de valeur qui s'est échappée d'un endroit sûr, confortable et pratique.
- La cible a une raison de partir que les PJs comprendront.
- La cible a démarré une nouvelle aventure (comme protagoniste ou comme victime), ce qui amène les PJ à entrer, eux-aussi, dans cette aventure.
- La "personne manquante" est un groupe ayant formé une expédition ou un pèlerinage d'une certaine sorte.
- La cible ne s'est pas enfuie, et n'est ni perdue, ni portée disparue, elle est seulement une cible que les PJ ont été embauchés pour retrouver (possiblement sous de faux prétextes).

* 19. Perte de mémoire

Un ou plusieurs des PJ se réveillent sans souvenirs récents, et sont mêlés à des problèmes qu'ils ne comprennent pas. Les PJs doivent découvrir la raison de leur perte de mémoire, et résoudre tous les problèmes qui se posent à eux pendant ce temps.

/Thèmes et rebondissements courants/ :
- Les PJs ont volontairement supprimé ou effacé leurs souvenirs, et ils découvrent qu'ils sont en train de défaire ce qu'ils avaient fait.

* 20. Très étrange, maman

Quelque chose d'à la fois mauvais et d'inexplicable se déroule (une tension raciale enflamme la ville, les débits de bières sont vides, il neige en juillet, le groupe Voyager a encore des fans, des hordes d'aliens sont en train de manger tous les fromages), ce qui inquiète beaucoup de nombreuses personnes. Les PJ doivent remonter à la source du phénomène et le stopper.

/Thèmes et rebondissements courants/ :
- Les PJ sont involontairement responsables de toute l'histoire.
- Ce qui semble être un problème d'une certaine sorte (technologique, personnelle, biologique, chimique, magique, politique, etc.) est en fait un problème d'une autre sorte.

* 21. Personne n'a sali le pont

On assigne aux PJ la tâche de garder un endroit vital (cela peut-être n'importe quoi, depuis un passage dans une montagne jusqu'à un système solaire) contre une attaque imminente ou possible. Ils doivent planifier leur stratégie de défense, régler leurs montres, etc., et affronter l'ennemi quand il arrive.

/Thèmes et rebondissements courants/ :
- Les renseignements fournis aux PJ s'avèrent erronés. Agir sur la base des nouvelles informations pourrait impliquer de grands dangers, tout comme ne pas agir en les considérant. Les PJs doivent choisir ou construire un compromis.
- Les PJs apprennent que l'ennemi a une bonne raison pour détruire l'endroit, raison qui attire la sympathie des PJs.

* 22. Pas au Kansas

Les PJs s'occupent de leurs affaires quand ils se trouvent transportés dans un endroit étrange. Ils doivent comprendre où ils sont, pourquoi ils sont là et comment s'échapper.

/Thèmes et rebondissements courants/ :
- Ils ont été emmenés là spécifiquement pour aider une personne ayant des ennuis.
- Ils se sont retrouvés là par accident, ou un effet collatéral de quelque chose d'étrange  et de secret.
- Quelques ennemis des PJ ont été transportés avec eux (ou séparément). Ils ont maintenant un nouveau champ de bataille, ainsi que des innocents qu'ils doivent convaincre que ce sont eux les gentils.

* 23. Des onces de prévention

Un méchant ou une organisation se prépare à faire quelque chose de mauvais, et les PJs ont reçu des tuyaux d'une certaine sorte. Ils doivent enquêter pour en apprendre plus sur le coup, et donc agir pour l'empêcher.

/Thèmes et rebondissements courants/ :
- Le tuyau initial était un leurre destiné à distraire les PJ du vrai coup.
- Il y a deux mauvais coups qui se préparent en même temps, et les PJs n'ont pas les moyens de les arrêter tous les deux. Comment choisir ?

* 24. La boîte de Pandore

Quelqu'un a joué avec des Choses Interdites à l'Homme, ou a ouvert un portail vers la dimension des Gens Méchants, troué un mur de prison, ou invoqué un ancien dieu babylonien sur la terrasse d'un appartement. Avant même que les PJ puissent penser à se confronter avec la source du problème, ils doivent gérer les vagues de problèmes créés par lui : des monstres, des vieux ennemis en recherche de vengeance, des aliens étranges qui pensent que les voitures ou les citoyens ou les hamburgers de chez McDonald ressemblent à de la nourriture, etc.

/Thèmes et rebondissements courants/ :
- Les PJs ne peuvent pas simplement prendre le mal libéré de haut : ils doivent le rassembler, et le renvoyer vers sa source avant que l'aventure prenne vraiment fin.
- Les PJs sont aspirés par la source et doivent résoudre des problèmes de l'autre côté avant de revenir vers le nôtre.
- Un livre secret, un code secret ou un autre élément rare est requis pour boucher la brêche (peut-être seulement le type qui l'a ouverte).
- Un cousin proche de cet intrigue est l'histoire basique : "quelqu'un a voyagé dans le passé et a tripatouillé notre réalité".

* 25. Une quête pour les beaux bleus

Quelqu'un a besoin d'un truc (pour remplir une prophécie, soigner un roi, empêcher une guerre, soigner une maladie, ou quoique vous ayez en stock). Les PJs doivent trouver un truc. Souvent un vieux truc, un truc mystérieux et puissant. Les PCs doivent en  apprendre sur lui pour pouvoir le rechercher, et ensuite trouver un moyen de le prendre là où il se trouve.

/Thèmes et rebondissements courants/ :
- Le truc est incomplet lorsque les PJs le trouvent (un des rebondissements les plus irritants et moins drôles de l'univers).
- Quelqu'un le possède déjà (ou l'a récemment volé, parfois avec une raison légitime).
- Le truc est une information, ou une idée, ou une substance, et non un truc spécifique.
- Les PJs doivent aller incognito infiltrer un groupe ou une société, obtenant le truc par ruse ou par un vol discret.

* 26. Des ruines récentes

Une ville, un chateau, un vaisseau spatial, un avant-poste ou une autre construction civilisée git en ruines. Jusqu'à très récemment, cet endroit était super. Les PJs doivent pénétrer dans les ruines, les explorer et trouver ce qui s'est passé.

/Thèmes et rebondissements courants/ :
- Quelque soit ce qui a détruit ces constructions (incluant des gens méchants, des radiations bizarres, des monstres, une nouvelle race, des fantômes, etc.) est toujours une menace ; les PJs doivent sauver la situation.
- Les habitants se sont autodétruits.
- Les "ruines" sont un vaisseau spatial délabré, récemment découvert.
- Les "ruines" sont une ville fantôme sur laquelle les PJs tombent au milieu de leur voyage - mais la carte dit que la ville existe et est vivante.

* 27. L'affrontement

Les PJs doivent voyager au travers d'une zone dangereuse, et la traverser sans être tués, volés, humiliés, avilis, infectés, ou rééduqué par ce qui s'y trouve. Les problèmes qu'ils rencontrent sont rarement de nature personnelle, l'endroit lui-même est le méchant de l'aventure.

/Thèmes et rebondissements courants/ :
- L'endroit n'est pas du tout dangereux, et les divers 'dangers" sont en fait des tentatives d'un agent d'une nature ou d'un autre, de communiquer avec les PJs.

* 28. Safari

Les PJs participent à un safari pour capture ou tuer une créature insaisissable et de valeur. Ils doivent faire face à son environnement, sa capacité à s'échapper et possiblement sa capacité à les combattre.

/Thèmes et rebondissements courants/ :
- La créature est immunisée à leurs appareils et à leurs armes.
- D'autres personnes protègent activement la créature.
- La tanière de la créature permet aux PJs de démarrer une autre aventure.

* 29. Un point pour l'équipe jouant à domicile

Les PJs participent à une course, un concours, un tournoi, une chasse au charognard ou quelqu'autre sorte de sport. Ils doivent gagner.

/Thèmes et rebondissements courants/ :
- Les autres participants sont moins honnêtes, et les PJs doivent surmonter leurs tentatives de gagner de manière malhonnête.
- Les PJs combattent pour quelque chose de plus profond que la victoire, par exemple pour protéger un autre participant, ou en espionner un, ou juste pour être à l'endroit où l'événement se passe.
- Les PJs ne souhaitent pas gagner ; ils veulent juste empêcher le méchant de gagner.
- L'événement est un test délibéré des compétences des PJs (pour entrer dans une organisation, par exemple).
- L'événement devient plus mortel qu'il n'était supposé être.

* 30. Stalag 23

Les PJs sont emprisonnés, et doivent construire un plan pour s'évader, vainquant les gardes, les mesures automatiques, et l'isolement géographique imposés par leur prison.

/Thèmes et rebondissements courants/ :
- Quelque chose est arrivé dans le monde extérieur et la sécurité de la prison est devenue laxiste pour cette raison.
- Les PJs ont été embauchés pour "tester" la prison, ce ne sont pas des prisonniers standards.
- D'autres prisonniers décident d'appeler à la révolte ou à la vengenace.
- Les PJs sont incognito pour espionner un prisonnier, mais sont ensuite pris pour de vrais prisonniers et restent incarcérés.
- Les PJs doivent s'échapper rapidement pour démarrer une autre aventure en dohors des murs.

* 31. Conduis-nous à Memphis et ne ralentis pas

Les PJs sont à bord d'un transport de personnes (East Indiaman, bateau de croisière, ferry, vaisseau spatial de transport, etc.) quand ce dernier est détourné. Les PJs doivent agir pendant les autres passagers restent assis et se tournent les pouces.

/Thèmes et rebondissements courants/ :
- Les "pirates" sont des agents du gouvernement impliqués dans une arnaque compliquée ; ils forcent les PJs à choisir un camp.
- Les pirates ne réalisent pas qu'il y a un danger secondaire dont ils doivent s'occuper ; toute tentative pour les convaincre est vu comme une blague.
- Les autres passagers n'aident pas ou sont même hostiles envers les PJs parce qu'ils pensent que ces derniers ne font qu'agraver la situation.

* 32. Les fauteurs de troubles

Un méchant (ou un groupe de méchants, ou de multiples groupes) crée du désordre, dérangeant les voisins, empoisonnant les réservoirs, ou tout autre chose créant des problèmes. Les PJs doivent aller dans l'endroit où se trouve le désordre, localiser les méchants et les arrêter.

/Thèmes et rebondissements courants/ :
- The PJs ne doivent pas blesser les fauteurs de troubles ; ils doivent être ramenés vivants et bien portants.
- Les méchants ont préparé quelque chose de dangereux et de caché comme "assurance" pour le cas où ils seraient capturés.
- Le "méchant" est un monstre ou un animal dangereux (ou une créature intelligente que touy le monde prend pour un monstre ou un animal).
- Le "méchant" est un personnage public respecté, un officier supérieur, ou quelqu'un d'autre qui abuse de son autorité ; les PJs pourraient rencontrer de l'hostilité de la part des parties prenantes habituellement aidantes, mais qui n'acceptent pas que le méchant soit méchant.
- Un équilibre des pouvoirs perpétue les problèmes ; les PJs doivent choisir leur camp pour rompre l'équilibre et arranger les choses.
- Le "problème" est diplomatique ou politique, et les PJs doivent créer la paix, pas la guerre.

* 33. Des sources non répertoriées

Les PJs sont des explorateurs et leur but est d'entrer dans un territoire inconnu et d'en déterminer la nature. Bien entendu, leur travail n'est pas juste de faire une enquête et de dessiner des spécimens de la faune locale ; quelque chose est là, quelque chose de fascinant et de menaçant.

/Thèmes et rebondissements courants/ :
- L'endroit est soit menaçant en lui-même (auquel cas les PJs doivent à la fois jouer au photographe de Geo et tenter de s'en échapper vivants, sains d'esprit et crédibles), soit l'endroit est de grande valeur et merveilleux, et quelque chose d'autres est là qui doit s'assurer que les PJs ne pourront pas propager l'information.
- D'autres conflits potentiels impliquent des dommages au moyen de transport des PJs et à leur équipement, auquel cas le scénario se transforme en /Ne mangez pas les violets/

* 34. Nous sommes en dehors regardant dedans

Toutes les intrigues basiques de cette liste peuvent être remodelées avec les PJs en dehors. Les PJs peuvent accompagner d'autres personnages qui sont au milieu de telles intrigues (ayant souvent été appelés pour résoudre l'intrigue de l'extérieur) ; ou ils peuvent être en train de se méler de leurs propres affaires lorsque ceux qui sont impliqués dans l'intrigue arrivent, forçant les PJs à prendre partie ou à simplement résister.

Par exemple, avec /Tout vieux port dans une tempête/, les PJs pourraient profiter de l'abri (ou en être natif) quand un groupe étrange arrive. Si la variante /les PJs sont mal accueillis/ est employée, alors il se peut que les PJs soient la seule voix de la raison pour contrer une ferveur religieuse, un préjudice racial, un sentiment anti-monstre, ou quoique ce soit d'autre qui soit la cause du conflit.

/Thèmes et rebondissements courants/ :
- Les PJs se retrouvent ceux à qui on donne à la fin de l'aventure.
- Prenez n'importe laquelle des intrigues de cette liste et renversez-là en plaçant les PJs dans le rôle des PNJs (souvent des méchants, des fugitifs, etc.). Au lieu de chasser, ils seront chassés. Au lieu de résoudre, ils doivent éviter de "se faire résoudre" (aïe).
- De manière alternative, laisser une intrigue classique telle qu'elle est mais retrournez les rebondissements, les transformants en super-rebondissements (ou dans de rafraîchissants contre-rebondissements).

* Trucs et astuces

** Le sens de la métaphore

J'ai écrit des intrigues dans la langue (tipyque très physique) du genre action-aventures, parce que c'est la forme basique du jeu de rôle d'aventures, mais si vous jouez sur plus de niveaux que cela, la liste peut quand même vous apporter beaucoup. Souvenez-vous seulement que chaque chose, endroit et ennemi peut réellement être une information, une personne, ou une attitude malsaine, aussi sûrement, qu'une station spatiale peut être un labyrinthe ("dungeon") et une trace magique peut être une emprunte.

** Le doublé

Une méthode basique amusante est le jeu du caméléon, où une aventure se présente comme un type d'histoire dans le niveau d'amorçage, puis se révèle être quelque chose d'autre.

Parfois, le changement est innocent et naturel. Par exemple, /Ne mangez pas les violets/ est un bon démarrage pour /L'affrontement/, et /Très étrange maman/ est une piste logique pour /La boîte de Pandore/.

Parfois, le changement est plus sinistre et délibéré, avec des PNJs vendant une aventure qui en est en réalité une autre. Cela peut toujours être innocent si les PNJs ont été dupés, ou s'ils sont juste si désespérément en recherche d'aide qu'ils pensent que personne n'aura le courage de s'attaquer au vrai problème.

** Lancez-vous un défi

Vos joueurs doivent pratiquer le plus tôt possible. Choisissez deux aventures aléatoires dans la Grande Liste et faites votre aventure de cela, quelque soit ce qui sorte : la première est le niveau d'amorce ; la seconde est la chair de l'aventure. Si la même entrée vient à deux reprises, alors faites avec ! Deux niveaux peuvent avoir la même structure mais de très différentes origines ou détails.

** Le doublé, deuxième partie

Certaines aventures très plaisantes sont tissées de deux intrigues séparées ou reliées par le thème. Une façon facile de faire marcher un tel dispositif est de créer une intrigue physique et une intrigue personnelle. Cela implique que juste une des intrigues pose une contrainte sur la localisation des PJs, tandis que la seconde peut les suivre partout.

Par exemple, les Pjs sont embauchés pour escorter un prince à un sommet de sorte qu'il puisse apparaître devant les masses pour annoncer la fin d'une guerre (une intrigue physique et un exemple simple de /Service d'escorte/). Mais au cours de l'aventure, les PJs réalisent que le pauvre garçon est suicidaire, parce que les obligations de l'état ont ruiné sa vie sentimentale ; ils doivent alors l'empêcher de s'autodétruire soit en résolvant le problème, soit en le convainquant d'accepter le poids des responsabilités (une intrigue personnelle et un exemple métaphorique de /Des onces de prévention/).

** Pas de panique

Un grand nombre de MJs utilisent la Grande Liste une fois seulement qu'ils ont commencé à paniquer. Ne vous flagellez pas trop rapidement ! En particulier, n'accordez pas trop d'importance à l'intrigue comme beaucoup de MJs le font.

Toutes les intrigues de cette liste peuvent fournir une structure qui fonctionne, et la structure est tout ce dont vous avez besoin pour une intrigue de jeu de rôles. Souvenez-vous d'exploiter les points forts du jeu de rôles, la plupart étant à propos des personnages, et non de l'intrigue. Ce n'est que dans un JDR que vous pouvez expérimenter un personnage fictionnel sur un plan personnel et direct. Mettez l'accent dans vos aventures sur ce point pour en tirer le maximum.

Toute intrigue qui contient plus qu'une structure basique risque de détourner l'attention vers quelque chose d'autre que les personnages, ce qui est un vrai gâchis. Tout ce dont vous avez besoin est de jouer avec les inflexions de l'histoire et de vous amusez en en rajoutant.

Relaxez-vous. Jouez.

** Et au final...

...voici /La petite liste des intrigues presque universelles qui marchent avec presque n'importe quelle intrigue/ :
- Les PJs doivent travailler avec un PNJ ou une organisation avec qui ils ne devraient pas devenie proches (ceux qui sont normalement des rivaux ou des méchants, ou juste un expert prétentieux envoyé pour les "aider", etc.).
- Les victimes sont des méchants et les méchants sont les véritables victimes.
- Les PJs rencontrent des gens qui peuvent les aider, mais qui ne le feront pas, à moins que les PJs les aident aussi dans leurs propres déboires.
- Le méchant est quelqu'un que les PJs connaissent personnellement, ou respectent, ou aiment (ou quelqu'un dont ils sont tombés amoureux au milieu de l'histoire).
- Les PJs doivent réussir sans violence et avec une discrétion spéciale.
- Les PJs doivent réussir sans avoir accès à des pouvoirs, de l'équipement ou une quelconque ressource qu'ils avaient généralement à leur disposition.
- Le méchant est, de manière récurrente, un faire-valoir.
- Un autre groupe, comparable à celui des PJs, a déjà échoué, et leurs corps/équipements/etc. fournissent des indices pour aider les PJs à faire mieux.
- Les PJs doivent protéger des innocents pendant l'aventure.
- L'aventure démarre soudainement et sans avertissement préalable. Les PJs sont jetés dans le feu de l'action dès la première scène.
- Les PJs doivent prétendre être d'autres personnes, ou ils restent qui ils sont mais doivent prétendre qu'ils ont des allégeances, des valeurs ou des goûts très différents. 
- Les PJs ne peuvent pas tout faire et sont obligés de choisir le mal qu'ils vont contrecarrer, les innocents qu'ils vont secourir, les valeurs ou l'idéal qu'ils vont défendre.
- Les PJs doivent faire un sacrifice personnel ou d'autres vont souffrir.
- On ne demande pas aux PJs de résoudre le problème, mais juste de fournir de l'aide dans le contexte d'un plus grand problème : prendre part à un transport de vivres, faire sortir en cachette un patient ayant besoin d'assistance médicale, etc.
- Un des PJ est (ou est présumé être) un héritier perdu, l'accomplissement d'une prophétie, un dieu volcan, ou une autre forme de sauveur et/ou de bouc-émissaire, ce qui est la cause de l'aventure.
- Un autre groupe de personnages, ressemblant aux PJs, sont en compétition avec eux, possiblement avec des buts différents quand à l'aboutissement.

* A propos de la liste

Cette révision de la Grande Liste est le fruit de plusieurs années supplémentaires de jeux, de conception de jeux, et, avec un peu de chance, de sagesse accumulée. C'est aussi le fruit de lettres de lecteurs qui m'ont titillé quand j'avais négligé quelque chose d'important !

Toutes les suggestions pour étendre cette liste doivent m'être envoyées par email. Elles seront accueillies à bras ouverts avec des bisous baveux. Vous pouvez aussi télécharger cet article sous la forme d'un fichier PDF très classe en visitant la page des téléchargements [insert link here]. Si vous avez aimé cet article, baladez-vous sur le site ou visitez le site de ma société Cumberland Games & Diversions. Le site contient plus d'une centaine de pages parlant de sujets liés au jeux et contient les tonnes de fichiers gratuits à télécharger.

La Grande Liste des intrigues de JDR est dédiée à tous les fans qui m'ont fait savoir à quel point elle avait été utile, et spécialement à ceux qui m'ont aidé à la rendre meilleure : Peter Barnard, Glen Barnett, Colin Clark, David Lott, Jason Puckett, Marc Rees, Carrie Schutrick, et Jeff Yaus, plus quelques mystérieux héros qui ne m'ont jamais donné leur véritable identité. Cette liste est dédiée à tous les MJs qui donnent à leur joueurs de longues et agréables heures de jeux.

Le contenu de cette page est Copyright ©1999, 2002 - S. John Ross.


