* Page about Fudge / Page sur Fudge

** Liens Fudge

Tout d'abord quelques liens :

- Le site [[https://fudgerpg.com/][Grey Ghost Press]] propose le jeu de rôle [[https://fudgerpg.com/about/about-fudge/fudge-overview.html][Fudge]] en téléchargement,
- Un site français a été fait sur Fudge [[http://fudge.ouvaton.org/][fudge.ouvaton.org]] avec un gros travail de traduction ;
  - Pour autant, la traduction est souvent peu utilisable,
  - A noter sur le site une [[http://fudge.ouvaton.org/files/FATE%25202.0%2520VF_v7.pdf][traduction en français de Fate 2.0]].

** Qu'est-ce que Fudge ?

*** Un hack de GURPS

N'y allons pas par quatre chemins : Fudge est un hack de GURPS qui vise à compenser les "défauts" suivants de GURPS :

- Des caractéristiques figées ;
- Un problème pour jouer à des échelles différentes (par exemple des lapins ou des robots géants) ;
- Une certaine complexité des règles.

Pour autant, malgré les apparences, Fudge reprend de très nombreuses choses de GURPS, en les modernisant un peu :

- Un système basé sur des caractéristiques et des compétences ;
- Un système basé sur des modificateurs avec une bonne dose de concours ("contest").

Certaines parties du jeu (par exemple, magie ou pouvoirs psioniques) sont même à la limite de l'incompréhensible si l'on ne connaît pas les règles correspondantes de GURPS.

*** Les plus

En gros, il est possible d'adapter plus ou moins tous les jeux à Fudge, car le système est très souple. Par contre, il ne faut pas minimiser le travail que cela demande, car les règles de Fudge sont quand même très ouvertes voire vagues à plus d'un endroit.

Fudge apporte aussi un bon compromis entre modernité et ancienneté. Fondamentalement, c'est un système classique mais avec une échelle de difficultés contenant des adjectifs, ce qui le rend moins "old school".

*** Les moins

Le problème de ne pas avoir de caractéristiques et de compétences figées est qu'il est donc difficile de créer une "collection" de suppléments. Aussi, le matériel pour Fudge est assez pauvre et quand bien même il existerait, il ne serait pas forcément compatible avec le Fudge que vous avez customisé pour vos propres besoins.

Ainsi, si nous regardons [[Department13.org][Department 13]], les caractéristiques sont les suivantes :
- Force,
- Agilité,
- Pouvoir,
- Lumière.

Il est facile d'adapter des jeux sur ces caractéristiques, mais l'inverse n'est pas forcément vrai.

*** Fate et les jeux à la mode

La gamme Fate a pris un chemin un peu différent. Capitalisant sur les notions d'échelle et de compétences, Fate a contraint le système pour créer une gamme de suppléments. Comme pas mal de jeux à la mode, Fate propose des archétypes de personnages (ou clichés ou concepts ou aspects, etc.), chose que l'on ne trouve pas nativement dans Fudge.

*** Fudge, le bonheur des vieux MJ hackers avec un peu de temps libre ?

Je pense que Fudge est un toolkit pour les vieux hackers qui veulent un système simple et souple et très adaptable à ce qu'ils veulent jouer, souvent du contenu personnel ou trouvé dans un autre jeu.


** Les ressources en français sur ce site

Règles :

- [[https://github.com/orey/jdr/blob/master/Fudge-fr/FudgeEnUnePage/FudgeEnUnePage-ORey05.pdf][Fudge en une page]]
- Division 13

** English resources in this repo

Fudge settings:

- [[FudgeDungeonCrawl.org][Fudge Dungeon Crawl]]
- [[http://www.batintheattic.com/downloads/MajesticRealmsRPG_Fudge_Rev%252016.zip][Majectic Realm RPG for Fudge/Fate]]

Fudge extensions:

- [[file:OtherUsesForFu.org][Other uses for Fudge Fu]]
- [[BuildingBetterSpaceships.org][Building better spaceships]]




